export const CREATE_ARTICLE_REQUEST = 'CREATE_ARTICLE_REQUEST'
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS'
export const CREATE_ARTICLE_FAIL = 'CREATE_ARTICLE_FAIL'
export const CREATE_ARTICLE_REMOVE = 'CREATE_ARTICLE_REMOVE'

export const LIST_ARTICLE_REQUEST = 'LIST_ARTICLE_REQUEST'
export const LIST_ARTICLE_SUCCESS = 'LIST_ARTICLE_SUCCESS'
export const LIST_ARTICLE_FAIL = 'LIST_ARTICLE_FAIL'
