export const CREATE_ASSESMENT_REQUEST = 'CREATE_ASSESMENT_REQUEST'
export const CREATE_ASSESMENT_SUCCESS = 'CREATE_ASSESMENT_SUCCESS'
export const CREATE_ASSESMENT_FAIL = 'CREATE_ASSESMENT_FAIL'
export const CREATE_ASSESMENT_REMOVE = 'CREATE_ASSESMENT_REMOVE'

export const ASSESMENT_BY_ID_REQUEST = 'ASSESMENT_BY_ID_REQUEST'
export const ASSESMENT_BY_ID_SUCCESS = 'ASSESMENT_BY_ID_SUCCESS'
export const ASSESMENT_BY_ID_FAIL = 'ASSESMENT_BY_ID_FAIL'