export const CREATE_EDUPROGRAM_REQUEST = 'CREATE_EDUPROGRAM_REQUEST'
export const CREATE_EDUPROGRAM_SUCCESS = 'CREATE_EDUPROGRAM_SUCCESS'
export const CREATE_EDUPROGRAM_FAIL = 'CREATE_EDUPROGRAM_FAIL'
export const CREATE_EDUPROGRAM_REMOVE = 'CREATE_EDUPROGRAM_REMOVE'

export const LIST_EDUPROGRAM_REQUEST = 'LIST_EDUPROGRAM_REQUEST'
export const LIST_EDUPROGRAM_SUCCESS = 'LIST_EDUPROGRAM_SUCCESS'
export const LIST_EDUPROGRAM_FAIL = 'LIST_EDUPROGRAM_FAIL'