export const CREATE_WORKSHOP_REQUEST = 'CREATE_WORKSHOP_REQUEST'
export const CREATE_WORKSHOP_SUCCESS = 'CREATE_WORKSHOP_SUCCESS'
export const CREATE_WORKSHOP_FAIL = 'CREATE_WORKSHOP_FAIL'
export const CREATE_WORKSHOP_REMOVE = 'CREATE_WORKSHOP_REMOVE'

export const LIST_WORKSHOP_REQUEST = 'LIST_WORKSHOP_REQUEST'
export const LIST_WORKSHOP_SUCCESS = 'LIST_WORKSHOP_SUCCESS'
export const LIST_WORKSHOP_FAIL = 'LIST_WORKSHOP_FAIL'
